<?php
/**
 * UpdateVanityNumberByIdParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DialMyCalls
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DialMyCalls;

/**
 * UpdateVanityNumberByIdParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description UpdateVanityNumberByIdParameters
/**
 * @package     DialMyCalls
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateVanityNumberByIdParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UpdateVanityNumberByIdParameters"
     */
    public function testUpdateVanityNumberByIdParameters()
    {

    }

    /**
     * Test attribute "callOptions"
     */
    public function testPropertyCallOptions()
    {

    }

    /**
     * Test attribute "recordingSource"
     */
    public function testPropertyRecordingSource()
    {

    }

    /**
     * Test attribute "specificRecordingId"
     */
    public function testPropertySpecificRecordingId()
    {

    }

    /**
     * Test attribute "playCta"
     */
    public function testPropertyPlayCta()
    {

    }

    /**
     * Test attribute "pttNumberId"
     */
    public function testPropertyPttNumberId()
    {

    }

}
