<?php
/**
 * PushToTalk
 *
 * PHP version 5
 *
 * @category Class
 * @package  DialMyCalls
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DialMyCalls\Models;

use \ArrayAccess;

/**
 * PushToTalk Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     DialMyCalls
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PushToTalk implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PushToTalk';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'type' => 'string',
        'calleridId' => 'string',
        'ringtone' => 'string',
        'cpm' => 'int',
        'addMessage' => 'object'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'type' => 'type',
        'calleridId' => 'callerid_id',
        'ringtone' => 'ringtone',
        'cpm' => 'cpm',
        'addMessage' => 'add_message'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'type' => 'setType',
        'calleridId' => 'setCalleridId',
        'ringtone' => 'setRingtone',
        'cpm' => 'setCpm',
        'addMessage' => 'setAddMessage'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'type' => 'getType',
        'calleridId' => 'getCalleridId',
        'ringtone' => 'getRingtone',
        'cpm' => 'getCpm',
        'addMessage' => 'getAddMessage'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['calleridId'] = isset($data['calleridId']) ? $data['calleridId'] : null;
        $this->container['ringtone'] = isset($data['ringtone']) ? $data['ringtone'] : null;
        $this->container['cpm'] = isset($data['cpm']) ? $data['cpm'] : null;
        $this->container['addMessage'] = isset($data['addMessage']) ? $data['addMessage'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type The add-on type. Option: ptt
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets calleridId
     * @return string
     */
    public function getCalleridId()
    {
        return $this->container['calleridId'];
    }

    /**
     * Sets calleridId
     * @param string $calleridId Phone number to connect the caller to.
     * @return $this
     */
    public function setCalleridId($calleridId)
    {
        $this->container['calleridId'] = $calleridId;

        return $this;
    }

    /**
     * Gets ringtone
     * @return string
     */
    public function getRingtone()
    {
        return $this->container['ringtone'];
    }

    /**
     * Sets ringtone
     * @param string $ringtone The ringtone to play to the user when connecting. Options: <a href=\"/onhold/elevator.mp3\" target=\"_blank\">elevator_music</a>, <a href=\"/onhold/islandfever.mp3\" target=\"_blank\">caribbean_music</a>, <a href=\"/onhold/mozartmarch.mp3\" target=\"_blank\">classical_music</a>, <a href=\"/onhold/digitalring.mp3\" target=\"_blank\">digital_ringing</a>, <a href=\"/onhold/oldring.mp3\" target=\"_blank\">old_phone_ringing</a>, <a href=\"/onhold/whenim46.mp3\" target=\"_blank\">goofy_music</a>
     * @return $this
     */
    public function setRingtone($ringtone)
    {
        $this->container['ringtone'] = $ringtone;

        return $this;
    }

    /**
     * Gets cpm
     * @return int
     */
    public function getCpm()
    {
        return $this->container['cpm'];
    }

    /**
     * Sets cpm
     * @param int $cpm Calls per minute throttling.
     * @return $this
     */
    public function setCpm($cpm)
    {
        $this->container['cpm'] = $cpm;

        return $this;
    }

    /**
     * Gets addMessage
     * @return object
     */
    public function getAddMessage()
    {
        return $this->container['addMessage'];
    }

    /**
     * Sets addMessage
     * @param object $addMessage Add a generic add-on message.
     * @return $this
     */
    public function setAddMessage($addMessage)
    {
        $this->container['addMessage'] = $addMessage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\DialMyCalls\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\DialMyCalls\ObjectSerializer::sanitizeForSerialization($this));
    }
}


