<?php
/**
 * CallerIdsTest
 * PHP version 5
 *
 * @category Class
 * @package  DialMyCalls
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DialMyCalls;

use \DialMyCalls\Configuration;
use \DialMyCalls\ApiClient;
use \DialMyCalls\ApiException;
use \DialMyCalls\ObjectSerializer;

/**
 * CallerIdsTest Class Doc Comment
 *
 * @category Class
 * @package  DialMyCalls
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CallerIdsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createCallerId
     *
     * Add Caller ID.
     *
     */
    public function testCreateCallerId()
    {

    }

    /**
     * Test case for createUnverifiedCallerId
     *
     * Add Caller ID (Unverified).
     *
     */
    public function testCreateUnverifiedCallerId()
    {

    }

    /**
     * Test case for deleteCallerIdById
     *
     * Delete Caller ID.
     *
     */
    public function testDeleteCallerIdById()
    {

    }

    /**
     * Test case for getCallerIdById
     *
     * Get Caller ID.
     *
     */
    public function testGetCallerIdById()
    {

    }

    /**
     * Test case for getCallerIds
     *
     * List Caller IDs.
     *
     */
    public function testGetCallerIds()
    {

    }

    /**
     * Test case for updateCallerIdById
     *
     * Update Caller ID.
     *
     */
    public function testUpdateCallerIdById()
    {

    }

    /**
     * Test case for verifyCallerIdById
     *
     * Verify Caller ID.
     *
     */
    public function testVerifyCallerIdById()
    {

    }

}
